import { useState } from 'react'
export default function Contato(){
 const [form,setForm]=useState({nome:'',email:'',telefone:'',assunto:'',mensagem:''})
 const submit=e=>{e.preventDefault();const m=['Olá! Gostaria de atendimento da NetData Computadores.','',`Nome: ${form.nome}`,`E-mail: ${form.email}`,`Telefone: ${form.telefone}`,`Assunto: ${form.assunto}`,`Mensagem: ${form.mensagem}`].join('\n');window.open('https://wa.me/554836222726?text='+encodeURIComponent(m),'_blank','noopener')}
 const change=e=>setForm({...form,[e.target.name]:e.target.value})
 return <>
 <section className="hero page-hero hero-contact" style={{padding:'80px 0 60px'}}><div className="hero-image"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=85" alt="" /></div><div className="hero-overlay"/><div className="container hero-content"><h1>Entre em contato</h1><p>Estamos prontos para atender você. Escolha a forma que preferir.</p></div></section>
 <section className="section"><div className="container"><div className="contact-grid"><div className="contact-info"><div className="contact-photo"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85" alt="Ambiente profissional de atendimento" loading="lazy"/></div><h3>Informações de contato</h3>
 <div className="contact-item"><div className="contact-item-icon">☎</div><div><strong>Telefone / WhatsApp</strong><a href="tel:+554836222726">(48) 3622-2726</a><br/><a href="https://wa.me/554836222726" target="_blank" rel="noopener noreferrer" style={{color:'var(--whatsapp)',fontWeight:600}}>Abrir WhatsApp</a></div></div>
 <div className="contact-item"><div className="contact-item-icon">✉</div><div><strong>E-mail</strong><a href="mailto:suporte@netdatacomputadores.com.br">suporte@netdatacomputadores.com.br</a></div></div>
 <div className="contact-item"><div className="contact-item-icon">⌖</div><div><strong>Endereço</strong><span>Rua Osvaldo Cruz, 219 - Centro<br/>88701-060 - Tubarão/SC</span></div></div>
 <div className="contact-item"><div className="contact-item-icon">◷</div><div><strong>Horário de atendimento</strong><span>Segunda a sexta, das 8h às 18h</span></div></div>
 <div style={{marginTop:30}}><a href="https://wa.me/554836222726?text=Olá! Gostaria de atendimento." className="btn btn-whatsapp" target="_blank" rel="noopener noreferrer">Falar no WhatsApp agora</a></div></div>
 <div className="contact-form"><h3>Envie uma mensagem</h3><form onSubmit={submit}><div className="form-group"><label htmlFor="nome">Nome *</label><input id="nome" name="nome" value={form.nome} onChange={change} required placeholder="Seu nome completo"/></div><div className="form-group"><label htmlFor="email">E-mail *</label><input type="email" id="email" name="email" value={form.email} onChange={change} required placeholder="seu@email.com"/></div><div className="form-group"><label htmlFor="telefone">Telefone / WhatsApp *</label><input type="tel" id="telefone" name="telefone" value={form.telefone} onChange={change} required placeholder="(48) 99999-9999"/></div><div className="form-group"><label htmlFor="assunto">Assunto *</label><select id="assunto" name="assunto" value={form.assunto} onChange={change} required><option value="">Selecione...</option><option value="orcamento">Solicitar orçamento</option><option value="manutencao">Manutenção / Reparo</option><option value="rede">Instalação de rede</option><option value="remoto">Suporte remoto</option><option value="outro">Outro assunto</option></select></div><div className="form-group"><label htmlFor="mensagem">Mensagem *</label><textarea id="mensagem" name="mensagem" value={form.mensagem} onChange={change} required placeholder="Descreva o problema ou a sua necessidade..."/></div><button type="submit" className="btn btn-blue" style={{width:'100%'}}>Enviar mensagem</button></form></div></div></div></section>
 </>
}