import PageMeta from '../components/PageMeta'
import { Link } from 'react-router-dom'
const items=[['Manutenção','Diagnosticamos e reparamos problemas no sistema. Também fazemos manutenção preventiva para evitar falhas futuras.'],['Troca de peças','Reparo e substituição de componentes queimados ou que pararam de funcionar (fonte, memória, HD/SSD, placa-mãe etc.).'],['Instalação de rede','Montagem e configuração de rede local para residências e empresas de qualquer porte.'],['Periféricos','Conserto e configuração de impressoras, monitores, scanners e outros equipamentos.'],['Segurança','Reforço da segurança do computador (antivírus, firewall, boas práticas) para uso pessoal ou empresarial.'],['Backup','Backup completo dos seus dados. Entregamos no formato que você preferir: HD externo, pendrive, DVD ou nuvem.']]
export default function Servicos(){return <><PageMeta title="Nossos Serviços | NetData Computadores" description="Serviços de assistência técnica, manutenção, redes, segurança e backup em Tubarão/SC." />
<section className="hero page-hero hero-services page-hero-modern" style={{padding:'80px 0 60px'}}><div className="hero-image"><img src="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1800&q=85" alt="" /></div><div className="hero-overlay"/><div className="container hero-content"><span className="hero-badge"><span className="hero-badge-dot" /> NetData Computadores</span><h1>Nossos Serviços</h1><p>Soluções completas para computadores, notebooks e redes em Tubarão e região.</p></div></section>
<section className="section"><div className="container"><div className="section-header"><span className="section-label">Atendimento técnico</span><h2>Soluções para manter sua tecnologia funcionando</h2><p>Serviços realizados com diagnóstico, orientação e foco em confiabilidade.</p></div><div className="services-grid">{items.map(([t,p])=>{const imageMap={'Manutenção': ['https://www.hippopx.com/en/free-photo-zhmvb','Manutenção de computador'],'Troca de peças': ['https://www.htmlvalidator.com/jpg/2019build/Asus-Strix-Gaming-X470-AMD-2600X-SSD-DDR4.jpg','Componentes e peças de computador'],'Instalação de rede': ['https://images.squarespace-cdn.com/content/v1/58d90911725e25ffc9bd5786/f7356c7e-2cb1-47c6-817a-21d4b643d123/8bc83f16c6053e72f5955f6e54db4b62c9a276f8f659dc8a061a62264ceaa2de.jpg','Cabos e infraestrutura de rede'],'Periféricos': ['https://www.undp.org/sites/g/files/zskgke326/files/2025-12/whatsapp_image_2025-12-11_at_21.03.32_1.jpeg','Monitor e periféricos'],'Segurança': ['https://www.softline.de/fileadmin/softline-group.co.uk/Pages/Blog/cybersecurity-concept-collage-design.jpg','Segurança digital'],'Backup': ['https://rebelgrowth.s3.us-east-1.amazonaws.com/blog-images/cloud-backup-solutions-monterey-ca-small-business-1.jpg','SSD externo e armazenamento para backup']};const [src,alt]=imageMap[t];return <div className="service-card" key={t}><div className="service-image"><img src={src} alt={alt} loading="lazy"/></div><h3>{t}</h3><p>{p}</p></div>})}</div></div></section>
<section className="section section-alt service-feature"><div className="container two-cols"><div className="image-card"><img src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=85" alt="Equipe trabalhando com tecnologia" loading="lazy"/></div><div><span className="section-label">Para empresas e residências</span><h2>Atendimento próximo, técnico e transparente</h2><p>Da manutenção de um notebook à configuração de uma rede, avaliamos a necessidade e indicamos a solução adequada.</p><Link to="/contato" className="btn btn-blue">Solicitar atendimento</Link></div></div></section>
<section className="section section-alt"><div className="container" style={{maxWidth:720,textAlign:'center'}}><h2 style={{marginBottom:16,color:'var(--secondary)',fontWeight:800}}>Garantia de tranquilidade</h2><p style={{color:'var(--text-muted)',marginBottom:28,fontSize:'1.05rem'}}>Todas as operações realizadas pela NetData são acompanhadas de um seguro que garante que você não terá prejuízo caso o reparo não seja possível ou a instalação de rede não possa ser concluída.</p><a href="https://wa.me/554836222726?text=Olá! Gostaria de um orçamento de serviço." className="btn btn-whatsapp" target="_blank" rel="noopener noreferrer">Solicitar orçamento no WhatsApp</a></div></section>
<section className="cta-banner"><div className="container"><h2>Marque um horário de atendimento</h2><p>Atendimento em domicílio ou remoto. Você escolhe o melhor dia e horário.</p><div className="cta-buttons"><Link to="/contato" className="btn btn-blue">Entre em contato</Link><a href="https://wa.me/554836222726" className="btn btn-outline" target="_blank" rel="noopener noreferrer">WhatsApp</a></div></div></section>
</>}